<?php

use App\Http\Controllers\DoctorController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\SustainabilityController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

// Dashboard for logged users
Route::get('/dashboard', function () {
    $user = auth()->user();
    $appointments = \App\Models\Appointment::with('doctor')
        ->where('user_id', $user->id)
        ->orderBy('date', 'desc')
        ->limit(5)
        ->get();
    
    $totalAppointments = \App\Models\Appointment::where('user_id', $user->id)->count();
    $upcomingAppointments = \App\Models\Appointment::with('doctor')
        ->where('user_id', $user->id)
        ->where('date', '>=', now())
        ->where('status', '!=', 'cancelled')
        ->count();
    
    return view('dashboard', compact('appointments', 'totalAppointments', 'upcomingAppointments'));
})->middleware(['auth', 'verified'])->name('dashboard');

// Profile routes (generated by Breeze)
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// -------------------
// Doctor + Appointment Routes
// -------------------
Route::middleware(['auth'])->group(function () {

    // List all doctors
    Route::get('/doctors', [DoctorController::class, 'index'])->name('doctors.index');

    // Show doctor details
    Route::get('/doctors/{doctor}', [DoctorController::class, 'show'])->name('doctors.show');

    // List all appointments
    Route::get('/appointments', [AppointmentController::class, 'index'])->name('appointments.index');

    // Create appointment form
    Route::get('/appointments/create', [AppointmentController::class, 'create'])->name('appointments.create');

    // Create appointment POST
    Route::post('/appointments', [AppointmentController::class, 'store'])->name('appointments.store');

    // RSE dashboard
    Route::get('/rse', [SustainabilityController::class, 'dashboard'])->name('rse.dashboard');

});

require __DIR__.'/auth.php';
